package Lucky38.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.InstanceMethodDeclaration_BehaviorDescriptor;

public class newFuncDecloration_BehaviorDescriptor extends InstanceMethodDeclaration_BehaviorDescriptor {
  public newFuncDecloration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Lucky38.structure.newFuncDecloration";
  }
}
