package Lucky38.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.ForStatement_BehaviorDescriptor;

public class newForStatment_BehaviorDescriptor extends ForStatement_BehaviorDescriptor {
  public newForStatment_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Lucky38.structure.newForStatment";
  }
}
