package Lucky38.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class newIfStatment_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public newIfStatment_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Lucky38.structure.newIfStatment";
  }
}
