package nextForth.sandbox;

/*Generated by MPS */


public class baseLang {


  public static void main(String[] args) {


    int i = 0;
    if (i == 0) {
      i = 1;
    }
    return;
  }



  public void lastFunc() {
  }





  public void NAME() {
    int n = 0;
    lastFunc();
  }







}
