package nextForth.sandbox;

/*Generated by MPS */


public class baseLang {



  public void myFunc() {
    int i = 0;
  }






  public static void main(String[] args) {


    int i = 0;

    return;
  }






}
