package Lucky38.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Expression_BehaviorDescriptor;

public class NewFuncReference_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public NewFuncReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "Lucky38.structure.NewFuncReference";
  }
}
